### ISSUE TITLE
Установка не завершается

### ISSUE THREAD

**Issue by localhostech** [vgrish/modTelegram#1]
При установке пакета не процесс не завершается и в Консоли вот такое предупреждение.

**PHP warning: require_once(/var/www/vh86323/data/www/hackside.ru/core/components/modtelegram/vendor/pusher/lib/Pusher.php): failed to open stream: No such file or directory**

**Comment by vgrish** [comment]
Привет, попробуй переустановить компонент. Возможно установка не укладывается в таймаут…

**Comment by localhostech** [comment]
Уже несколько раз переустанавливал. Раньше устаналивал на многих сайтах, и вот сейчас пробую установить и ни на один не устанавливается, пробовал на трех сайтах. Мне почему-то кажется, что проблема возникает из-за Pusher. Может быть у них были какие-то обновления в последнее время?

**Comment by localhostech** [comment]
Да, точно так и есть. У них сейчас файл **Pusher.php** располагается не в директории **vendor/pusher/lib/Pusher.php**, а в **vendor/pusher/src/Pusher.php**

**Comment by vgrish** [comment]
вполне возможно, посмотрю как будет время, спасибо!

**Comment by vgrish** [comment]
поправил...
